<?php

namespace AppBundle\Repository;



/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllbyPagination()
    {
        $qb = $this->createQueryBuilder('m');
        $qb->addSelect('m')
            ->addOrderBy('m.title', 'ASC')
        ;
        $query = $qb->getQuery();

        return $query;
    }
}
