<?php

namespace AppBundle\Repository;

/**
 * WishedFilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishedFilmRepository extends \Doctrine\ORM\EntityRepository
{
}
