home:
    path:     /
    defaults: { _controller: AppBundle:Film:home }

getall:
    path:     /get-all
    defaults: { _controller: AppBundle:Film:getAll }

getfilm:
    path:     /get-film/{id}
    defaults: { _controller: AppBundle:Film:getDetail }

getByPeople:
    path:     /get-film-by-people/{imdbId}
    defaults: { _controller: AppBundle:Film:getByPeople }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

wishlist_add:
    path:     /wishlist-add/{id}
    defaults: { _controller: AppBundle:Wished:add }

wishlist_remove:
    path:     /remove-wishlist/{id}
    defaults: { _controller: AppBundle:Wished:remove }


wishlist:
    path:     /wishlist
    defaults: { _controller: AppBundle:Wished:getAll }


ajaxFilm:
    path:     /api/{nom}
    defaults:
        _controller: AppBundle:Film:ajax
        nom: