home:
    path:     /
    defaults: { _controller: AppBundle:Film:home }

getall:
    path:     /get-all
    defaults: { _controller: AppBundle:Film:getAll }

getfilm:
    path:     /get-film/{id}
    defaults: { _controller: AppBundle:Film:getDetail }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

wishlist:
    path:     /wishlist/{id}
    defaults: { _controller: AppBundle:Wished:add }

wishlist_remove:
    path:     /remove-wishlist/{id}
    defaults: { _controller: AppBundle:Wished:remove }